name: edevice
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.1
  provider: ^6.0.4
  carousel_slider: ^4.1.1
  file_picker: ^5.0.1
  email_validator: '^2.1.16'
  flutter_svg: ^1.1.1+1
  modal_bottom_sheet: ^2.0.1
  easy_localization: ^3.0.1
  url_launcher: ^6.1.4
  flutter_linkify: ^5.0.2
  intl: ^0.17.0
  image_picker: ^0.8.6

  #Firebase
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/icons/
   - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700